"""Which geometric parameter moves the clot outcome most.

Reads the research-sweep summaries already generated by ``run_research_sweep.py`` /
``generate_research_sweep_fig_data.py`` (no new simulation) and ranks the single-axis sweeps
by the range of ``wall_clot_pct_final`` each one spans over the tested parameter values --
a tornado chart answering "stenosis strength vs. inlet width vs. ... -- which matters most",
using exactly the numbers already in ``table_research_sweeps.csv``.

Excluded from the ranking, deliberately:
  - the two-axis interaction sweeps (12_bend_x_stenosis, 18_wound_x_stenosis) -- their range
    conflates two parameters and belongs on the phase-diagram figure instead
    (``plot_critical_point.py``), not on a single-axis tornado;
  - 19_wound_vs_no_wound and 20_wound_stenosis_offset -- categorical arm comparisons, not a
    swept continuous/ordinal axis, so "range" is not the same kind of quantity.

Caveat that belongs beside every number here, not just in the report text: these are the
model's *response* to geometry constructed with no matching COMSOL ground truth at the
intermediate points (03_results.tex, "Geometry-response sweeps"), so a large range says the
surrogate is sensitive to that axis, not that the sensitivity is quantitatively correct.
"""
from __future__ import annotations

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from scripts.publication.config import CONFIG, RESEARCH_SWEEP_FIG_DIR
from scripts.publication.utils import setup_matplotlib_style

METRIC = "wall_clot_pct_final"

# (sweep_id, short axis label for the chart)
SINGLE_AXIS_SWEEPS = (
    ("04_inlet_width", "inlet width"),
    ("02_aneurysm_strength", "aneurysm strength"),
    ("01_stenosis_strength", "stenosis strength"),
    ("05_bendiness", "bendiness"),
    ("10_pathology_length", "pathology axial extent"),
    ("08_vessel_length", "vessel length"),
    ("16_wound_width", "wound patch width"),
    ("09_stenosis_eccentricity", "stenosis eccentricity"),
    ("14_wall_roughness", "wall roughness amplitude"),
    ("06_stenosis_location", "stenosis axial location"),
    ("17_wound_position", "wound axial position"),
)


def main() -> int:
    setup_matplotlib_style()
    csv_path = RESEARCH_SWEEP_FIG_DIR / "table_research_sweeps.csv"
    if not csv_path.is_file():
        print(f"[sensitivity] missing {csv_path}; run plot_research_sweep_figures.py first")
        return 1
    df = pd.read_csv(csv_path)

    rows = []
    for sid, label in SINGLE_AXIS_SWEEPS:
        sub = df[df["sweep_id"] == sid]
        if sub.empty:
            print(f"[sensitivity] no rows for {sid}, skipping")
            continue
        vals = pd.to_numeric(sub[METRIC], errors="coerce").dropna()
        if vals.empty:
            continue
        lo, hi = float(vals.min()), float(vals.max())
        rows.append({
            "sweep_id": sid,
            "label": label,
            "n_points": int(len(vals)),
            "min": lo,
            "max": hi,
            "range": hi - lo,
        })
    if not rows:
        print("[sensitivity] no sweep data found")
        return 1

    out = pd.DataFrame(rows).sort_values("range", ascending=True).reset_index(drop=True)
    out.to_csv(RESEARCH_SWEEP_FIG_DIR / "table_sensitivity_ranking.csv", index=False)

    fig, ax = plt.subplots(figsize=(6.5, 0.42 * len(out) + 1.0))
    y = np.arange(len(out))
    ax.barh(y, out["range"], left=out["min"], color=CONFIG.color_model, height=0.6)
    for yi, row in zip(y, out.itertuples()):
        ax.text(row.max + 0.5, yi, f"{row.range:.1f} pp", va="center",
                fontsize=CONFIG.font_size - 2)
    ax.set_yticks(y)
    ax.set_yticklabels([f"{r.label}  (n={r.n_points})" for r in out.itertuples()])
    ax.set_xlabel(f"{METRIC.replace('_', ' ')}, range over swept values (percentage points)")
    ax.set_title(
        "Which geometric axis moves the predicted clot burden most\n"
        "(model response only -- no COMSOL ground truth at these intermediate points)",
        loc="left", fontsize=CONFIG.font_size)
    ax.grid(axis="x", alpha=0.3)
    fig.tight_layout()

    out_path = RESEARCH_SWEEP_FIG_DIR / f"sensitivity_ranking.{CONFIG.fig_format}"
    fig.savefig(out_path)
    plt.close(fig)
    print(f"[sensitivity] wrote {out_path}")
    print(out[["label", "n_points", "min", "max", "range"]].to_string(index=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
